[build]
publish = "dist" # Replace with your actual build folder, typically "dist" for Vite
command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
  # Exclude static asset paths from the redirect
  conditions = { 
    "Language" = "en"
  }

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200




