[build]
publish = "dist" # Replace with your actual build folder, typically "dist" for Vite
command = "npm run build"

[[redirects]]
from = "/index.mjs"
to = "/index.mjs"
status = 200

[[redirects]]
from = "/index.js"
to = "/index.js"
status = 200


[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[[redirects]]
from = "/indexComments.js"
to = "/indexComments.js"
status = 200
