[build]
publish = "dist" # Replace with your actual build folder, typically "dist" for Vite
command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
conditions = { Accept = "text/html" }

# Explicitly allow .mjs and .js files to be served
[[redirects]]
  from = "/**.mjs"
  to = "/**.mjs"
  status = 200

[[redirects]]
  from = "/**.js"
  to = "/**.js"
  status = 200

[[redirects]]
  from = "/**.css"
  to = "/**.css"
  status = 200
